### ISSUE TITLE
Frenzy freezing while trying to calculate the clock deviation from a timeserver

### ISSUE THREAD

**Issue by pryley** [aptonic/frenzy#4] opened 2013-10-31 18:37 UTC
This happened a couple of times at a Starbucks. They have a free wifi network (AT&T), but the internet browsing is restricted to the Starbucks and AT&T websites until you accept the terms of use.

This particular Starbucks had so many people online that I think their router was overloaded or something. The internet was super slow and would randomly stop working and then start working again.

I don't remember if I experienced the freezing between the time I connected to the network and accepted the terms of use, or whether it was after I was fully connected to the internet.

**Comment by aptonic** [comment] 2013-11-01 02:57
Thanks - I've seen this issue before. From what I can remember it's caused by NSHost failing to do a DNS lookup and then hanging. I went to some lengths to resolve it including swizzling NSHost class methods but it still seems to persist in some circumstances. I'm going to close this for off for now. Am aware of the problem and if I think of another way to resolve it down the track then will be sure to fix. Fortunately it's a pretty rare occurrence.

**Closed as completed by aptonic** 2013-11-01 02:57 UTC
